In [1]:
import numpy as np

In [3]:
var = [1, 2, 3]

In [4]:
var[:2]

[1, 2]

In [14]:
# dtype，是numpy的数据类型
np.empty((3, 3), dtype=np.float32, order="C")

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [15]:
np.empty((3, 3), dtype=float, order="C")

array([[2.60605835e-31, 5.21211670e-31, 1.30302917e-31],
       [5.21211670e-31, 1.13363538e-30, 3.51817877e-31],
       [1.30302917e-31, 3.51817877e-31, 2.01969522e-31]])

In [13]:
np.empty((3, 3), dtype="float32", order="C")

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [16]:
#  float ->  4byte
#  float16 -> 2byte
#  int   ->  4byte 基本都是4字节
#  double -> 8byte
#  char  ->  1byte
#  short ->  2byte
#  long  ->  4byte  特定平台，会不一样
np.empty((3, 3), dtype="int16", order="C")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 8]], dtype=int16)

In [17]:
np.empty((3, 3), dtype="float16", order="C")

array([[0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 1.3336e+04, 5.4598e-04],
       [0.0000e+00, 8.1920e+03, 1.1921e-07]], dtype=float16)

In [21]:
# order  ->  
#help(np.empty)
# C 行排列  C-style         row-major
# F 列排列  Fortran-style   column-major
#help(np.empty)

In [31]:
# 1, 2, 3, 4, 5, 6
#
# 1, 2, 3;
# 4, 5, 6

# 1  3  5
# 2  4  6

In [35]:
np.zeros((3, 3), dtype=np.float32)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [36]:
np.ones((3, 3), dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [38]:
var = [1, 2, 3, 4, 5, 6]
np.asarray(var, dtype=np.float32).reshape(2, 3)  #  1-d  

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [41]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [44]:
array = np.ones((3, 3), dtype=np.float32)
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [45]:
array[0]

array([1., 1., 1.], dtype=float32)

In [46]:
isinstance(array, np.ndarray)

True

In [52]:
float32_array = np.ones((3, 3), dtype=np.float32)
float32_array.dtype

dtype('float32')

In [53]:
float32_array.shape

(3, 3)

In [54]:
np.ones(3).shape

(3,)

In [63]:
var = np.random.rand(3, 2, 3)
var

array([[[0.01247059, 0.75723157, 0.84895758],
        [0.26889179, 0.67597815, 0.95178653]],

       [[0.54101368, 0.56229286, 0.54662305],
        [0.05755899, 0.99693149, 0.17595181]],

       [[0.89430605, 0.71783512, 0.93100338],
        [0.83372609, 0.93479555, 0.76991226]]])

In [60]:
var[1, 1]

0.07939285421798603

In [61]:
var[:, 2]

array([0.44956314, 0.70744241, 0.55204863])

In [62]:
var[..., 2]

array([0.44956314, 0.70744241, 0.55204863])

In [64]:
var[2, 1, :]

array([0.83372609, 0.93479555, 0.76991226])

In [65]:
var[2, :, :]

array([[0.89430605, 0.71783512, 0.93100338],
       [0.83372609, 0.93479555, 0.76991226]])

In [66]:
var[2]

array([[0.89430605, 0.71783512, 0.93100338],
       [0.83372609, 0.93479555, 0.76991226]])

In [68]:
var[0:3:2]

array([[[0.01247059, 0.75723157, 0.84895758],
        [0.26889179, 0.67597815, 0.95178653]],

       [[0.89430605, 0.71783512, 0.93100338],
        [0.83372609, 0.93479555, 0.76991226]]])

In [77]:
var = np.ones((3, 3))
var

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
view = var.view()

In [79]:
view = view.reshape(1, 9)
view

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [81]:
var

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
view[0] = 10
view

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [84]:
var

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [85]:
var

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [87]:
var_copy = var.copy()
var_copy

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [89]:
var_copy[2, 2] = 5
var_copy

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10.,  5.]])

In [90]:
var

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [96]:
values = [1, 2, 3, 4, 5, 6]
array = np.asarray(values, dtype=np.float32)
array = array.reshape(2, 3)  #  只改变维度，不修改数据的操作
array = array.reshape(1, 6)
array

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

In [101]:
values = [1, 2, 3, 4, 5, 6]
array = np.asarray(values, dtype=np.float32).reshape(2, 3)
# 
array.shape

(2, 3)

In [103]:
# old: dim0 = 2,   dim1 = 3
# new: dim0 = 3,   dim1 = 2
#  1,  0
array.transpose(1, 0)

array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)

In [110]:
values = np.arange(0, 18)
array = np.asarray(values, dtype=np.float32).reshape(3, 2, 3)
array

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.]]], dtype=float32)

In [111]:
# old: height, width, channels
# new: channels, height, width
# 2, 0, 1
trans = array.transpose(2, 0, 1)

In [115]:
array[1, 1]

array([ 9., 10., 11.], dtype=float32)

In [129]:
trans[:]

array([[[ 0.,  3.],
        [ 6.,  9.],
        [12., 15.]],

       [[ 1.,  4.],
        [ 7., 10.],
        [13., 16.]],

       [[ 2.,  5.],
        [ 8., 11.],
        [14., 17.]]], dtype=float32)

In [119]:
# 0 = height, 1 = width, 2 = channels
# channels, height, width
# 2, 0, 1
# HWC -> 数据格式的代号    tensorflow -》  默认格式 ，  以及，他是opencv的默认读取格式，仅仅是C维度为BGR，比较奇葩，用的少
# CHW -> pytorch默认格式，以及tensorRT等架构通用的格式，这个比较通用

In [125]:
for index, value in enumerate(np.arange(0, 10)):
    print(index, value)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9


In [131]:
var = list(range(6))
var

[0, 1, 2, 3, 4, 5]

In [132]:
np.array(var).reshape(2, 3, order="C")

array([[0, 1, 2],
       [3, 4, 5]])

In [133]:
np.array(var).reshape(2, 3, order="F")

array([[0, 2, 4],
       [1, 3, 5]])

In [136]:
data = np.random.rand(3, 2)
data

array([[0.20712292, 0.80585897],
       [0.26562193, 0.29817816],
       [0.38081077, 0.15157592]])

In [140]:
np.hstack((data, np.ones((3, 1))))

array([[0.20712292, 0.80585897, 1.        ],
       [0.26562193, 0.29817816, 1.        ],
       [0.38081077, 0.15157592, 1.        ]])

In [141]:
np.vstack((data, np.ones((1, 2))))

array([[0.20712292, 0.80585897],
       [0.26562193, 0.29817816],
       [0.38081077, 0.15157592],
       [1.        , 1.        ]])

In [142]:
#  lr < 1 / beta
#
# w = w - lr * grad
mean(grad), sum(grad)
mean(grad) * batch_size = sum(grad)

w = w - (lr * batch_size) * grad

SyntaxError: can't assign to operator (<ipython-input-142-269be95b99b3>, line 5)

In [144]:
data = np.arange(60000)
data.shape

(60000,)

1. 迭代n个epochs
2. 每个epoch要打乱一次
3. 你得每次拿到一个batch_size的数据

In [150]:
batch_size = 256
num_batch_per_epoch = np.ceil(60000 / 256)
num_epochs = 300

In [151]:
num_batch_per_epoch

235.0

In [152]:
num_epochs * num_batch_per_epoch

70500.0